error handling

diff --git a/downloadsubtitle b/downloadsubtitle
--- a/downloadsubtitle
+++ b/downloadsubtitle
@@ -25,9 +25,17 @@ fi
 echo "Requested language: $lang"
 output=$(echo "$1" | sed 's/\.[^.]*$/.srt/')
 oshash=$(oshash "$1")
+if [ "$?" = 1 ]; then
+    echo "Error: oshash returned 1"
+    exit
+fi
 echo "Movie hash: $oshash"
 subid=$(wget "http://www.opensubtitles.org/en/search/sublanguageid-$lang/moviehash-$oshash/rss_2_00" -q -O - \
     | grep '.*en/subtitles' | sed 's|.*en/subtitles/||; s|/.*||' | head -n1)
+if [ -z "$subid" ]; then
+    echo "Error: subtitle not found"
+    exit
+fi
 echo "Subtitle ID: $subid"
 wget "http://www.opensubtitles.org/en/subtitleserve/sub/$subid" -q -O - | gunzip > "$output" 2> /dev/null
 echo "Subtitle: $output"
